#include <RSettings.h>
#include <GLFW/glfw3.h>

Settings::Settings()
{
	ControlToGLFWKeys = {
		{"FORWARD_KEY", GLFW_KEY_W},
		{"BACKWARD_KEY", GLFW_KEY_S},
		{"RIGHT_KEY", GLFW_KEY_D},
		{"LEFT_KEY", GLFW_KEY_A},
		{"EXIT_KEY", GLFW_KEY_ESCAPE},
		{"PLAY_KEY", GLFW_KEY_SPACE}
	};
	GLFWKeysToControl = {
		{GLFW_KEY_W,"FORWARD_KEY"},
		{GLFW_KEY_S,"BACKWARD_KEY"},
		{GLFW_KEY_D,"RIGHT_KEY"},
		{GLFW_KEY_A,"LEFT_KEY"},
		{GLFW_KEY_ESCAPE,"EXIT_KEY"},
		{GLFW_KEY_SPACE,"PLAY_KEY"}
	};
	ControlToGLFWMouseKeys = {
	   {"FORWARD_KEY", GLFW_KEY_W},
	   {"BACKWARD_KEY", GLFW_KEY_S},
	   {"RIGHT_KEY", GLFW_KEY_D},
	   {"LEFT_KEY", GLFW_KEY_A},
	   {"EXIT_KEY", GLFW_KEY_ESCAPE},
	   {"PLAY_KEY", GLFW_KEY_SPACE}
	};
	GLFWMouseKeysToControl = {
		{GLFW_KEY_W,"FORWARD_KEY"},
		{GLFW_KEY_S,"BACKWARD_KEY"},
		{GLFW_KEY_D,"RIGHT_KEY"},
		{GLFW_KEY_A,"LEFT_KEY"},
		{GLFW_KEY_ESCAPE,"EXIT_KEY"},
		{GLFW_KEY_SPACE,"PLAY_KEY"}
	};
}