#include <RSettings.h>
#include <GLFW/glfw3.h>
Settings::Settings()
{
	ControlToGLFWKeys = {
		{"FORWARD_KEY", GLFW_KEY_W},
		{"BACKWARD_KEY", GLFW_KEY_S},
		{"RIGHT_KEY", GLFW_KEY_D},
		{"LEFT_KEY", GLFW_KEY_A},
		{"EXIT_KEY", GLFW_KEY_ESCAPE},
		{"PLAY_KEY", GLFW_KEY_SPACE},
		{"RELOAD_SHADER_KEY",GLFW_KEY_GRAVE_ACCENT },
		{"RUN_KEY",GLFW_KEY_LEFT_SHIFT}
	};
	GLFWKeysToControl = {
		{GLFW_KEY_W,"FORWARD_KEY"},
		{GLFW_KEY_S,"BACKWARD_KEY"},
		{GLFW_KEY_D,"RIGHT_KEY"},
		{GLFW_KEY_A,"LEFT_KEY"},
		{GLFW_KEY_ESCAPE,"EXIT_KEY"},
		{GLFW_KEY_SPACE,"PLAY_KEY"},
		{GLFW_KEY_GRAVE_ACCENT,"RELOAD_SHADER_KEY"},
		{GLFW_KEY_LEFT_SHIFT,"RUN_KEY"}
	};
	ControlToGLFWMouseKeys = {
		{"ALT_CLICK_KEY", GLFW_MOUSE_BUTTON_RIGHT},
		{"CLICK_KEY", GLFW_MOUSE_BUTTON_LEFT},
		{"MIDDLE_CLICK_KEY", GLFW_MOUSE_BUTTON_MIDDLE}
	};
	GLFWMouseKeysToControl = {
		{GLFW_MOUSE_BUTTON_RIGHT,"ALT_CLICK_KEY"},
		{GLFW_MOUSE_BUTTON_LEFT,"CLICK_KEY"},
		{GLFW_MOUSE_BUTTON_MIDDLE,"MIDDLE_CLICK_KEY"}
	};
}